project:
  type: website
  output-dir: "docs"
  render:
    - "*.qmd"

# website:
#   title: "Physics Lab Work"
#   navbar:
#     left:
#       - text: "Home"
#         href: index.qmd
#       - text: "Statistik"
#         href: "S01 Statistik/S01.qmd"
#       # - text: "Lab 2"
#         # href: report-2/report-2.qmd
#     # You can add a link to the PDF output here once it's rendered
#     right:
#       - icon: github
#         href: https://github.com/Just-Neptun/FP

format:
  html: default
  pdf: default